services:
  - type: web
    name: smartbiz
    env: node
    plan: free
    buildCommand: npm install --prefix client && npm run build && npm run render:install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
